state = read.csv("statedataSimple.csv")
model = lm(Life.Exp~Population+Income+Illiteracy+Murder+HS.Grad+Frost+Area, data= state)
names(state)
summary(model1)
sum(model1$residuals^2)
model1= lm(Life.Exp~Population+Murder+Frost+HS.Grad, data = state)
cartm= rpart(Life.Exp~., data= state, minbucket=5)
prp(cartm1)
pred=predict(cartm)
sum((pred-state$Life.Exp)^2)
install.packages(caret)
library(caret)
set.seed(111)
library(e1071)
numfold = trainControl(method="cv",number=10)
cpgrid = expand.grid(.cp=seq(.01,.5,.01))
train(Life.Exp~Area,data = state,method="rpart",trControl=numfold,tuneGrid=cpgrid)
cartm1= rpart(Life.Exp~Area, data= state,cp=.01)
pred= predict(cartm1)
sum((pred-state$Life.Exp)^2)
prp(cartm1)