vote=read.csv("gerber.csv")
str(vote)
table(vote$voting)
108696/(108696+235388)
table(vote$voting,vote$hawthorne)
tapply(vote$voting,vote$civicduty,mean)
model=glm(voting~civicduty+hawthorne+self+neighbors,data=vote,family = binomial)
summary(model)
pred= predict(model,type="response")
table(vote$voting,pred>.5)
library(rpart)
cartm = rpart(voting~civicduty+hawthorne+self+neighbors,data=vote)
  prp(cartm4, digits = 6)
library(rpart.plot)
cartm1 = rpart(voting~civicduty+hawthorne+self+neighbors,data=vote,cp=0.0)
cartm2 = rpart(voting~civicduty+control+hawthorne+self+neighbors+sex,data=vote,cp=0.0)
cartm3=rpart(voting~control,data=vote,cp=0.0)
cartm4=rpart(voting~control+sex,data=vote,cp=0.0)
model1 = model=glm(voting~control+sex,data=vote,family = binomial)
summary(model1)
Possibilities = data.frame(sex=c(0,0,1,1),control=c(0,1,0,1))
predict(model2, newdata=Possibilities, type="response")
model2 = model=glm(voting~control+sex+control:sex,data=vote,family = binomial)
summary(model2)