rm(list=ls())
census = read.csv("census.csv")
set.seed(2000)
split = sample.split(census$over50k, SplitRatio = 0.6)
train = subset(census,split == TRUE)
test= subset(census, split==FALSE)
model = glm(over50k~., data = train, family = binomial)
summary(model)
pred = predict(model, newdata= test,type="response")
table(test$over50k,pred>0.5)
(9051+1888)/nrow(test)
table(test$over50k)
9713/(9713+3078)
predROCR = prediction(pred,test$over50k)
prefl = performance(predROCR,"tpr","fpr")
plot(prefl,colorize=TRUE, print.cutoffs.at=seq(0,1,0.1),text.adj=c(-0.2,1.7))
auc = as.numeric(performance(predROCR,"auc")@y.values)
CARTm = rpart(over50k~., data = train, method="class")
predc = predict(CARTm,newdata = test, type ="class")
predr = predict(CARTm,newdata = test)
table(test$over50k,predc)
(9243+1596)/nrow(test)
prp(CARTm)
predcart = prediction(predr[,2],test$over50k)
pref = performance(predcart,"tpr","fpr")
plot(pref, colorize=TRUE,print.cutoffs.at=seq(0,1,0.1),text.adj=c(-0.2,1.7))
auc = as.numeric(performance(predcart,"auc")@y.values)

trainSmall = train[sample(nrow(train),2000),]
set.seed(1)
randomModel = randomForest(over50k~., data = trainSmall)
predRandom = predict(randomModel, newdata = test)
table(predRandom,test$over50k)
(8878+1941)/nrow(test)
vu = varUsed(randomModel, count=TRUE)
vusorted = sort(vu, decreasing = FALSE, index.return = TRUE)
dotchart(vusorted$x, names(randomModel$forest$xlevels[vusorted$ix]))
varImpPlot(randomModel)
install.packages("caret")
library(caret)
install.packages("e1071")
library(e1071)
numfolds = trainControl(method = "cv",number=10)
cpGrid = expand.grid(.cp= seq(0.002,0.1,0.002))
train(over50k~.,data=train,method="rpart",trControl=numfolds,tuneGrid=cpGrid)
modelV = rpart(over50k~., data = train, method="class",cp=0.002)
predV = predict(modelV, newdata = test,type = "class")
table(test$over50k,predV)
(9178+1838)/nrow(test)
plot(modelV)
