rm(list=ls())
letter = read.csv("letters_ABPR.csv")
names(letter)
table(letter$letter)
letter$isB =as.factor(letter$letter=="B")
2350/(2350+766)
library(caTools)
split=sample.split(letter$isB,SplitRatio = 0.5)
train = subset(letter,split==TRUE)
test = subset(letter,split==FALSE)
CARTb = rpart(isB ~ . - letter, data=train, method="class")
pred = predict(CARTb, newdata = test,type = "class")
table(test$isB,pred)
install.packages("randomForest")
library(randomForest)
randomModel1 = randomForest(isB ~ . - letter, data=train)
pred2 = predict(randomModel1, newdata = test)
table(test$isB,pred2)
(1164+366)/nrow(test)
split=sample.split(letter$letter,SplitRatio = 0.5)
train1 = subset(letter,split==TRUE)
test1 = subset(letter,split==FALSE)
CARTb1 = rpart(letter ~ . - isB, data=train1, method="class")
pred1= predict(CARTb1, newdata = test1, type = "class")
table(test1$letter,pred1)
(351+293+370+345)/nrow(test1)
set.seed(1000)
randomModel = randomForest(letter ~ . - isB, data=train1)
pred3 = predict(randomModel, newdata = test1)
table(test1$letter,pred3)
(394+375+393+367)/nrow(test1)
