setwd("C:/Users/988003/Downloads")
gerber = read.csv("gerber.csv")
str(gerber)
table(gerber$voting)
108696/(108696+235388)
table(gerber$voting,gerber$hawthorne)
table(gerber$voting,gerber$civicduty)
table(gerber$voting,gerber$neighbors)
table(gerber$voting,gerber$self)
table(gerber$voting,gerber$control)
model = glm(voting ~ civicduty+hawthorne+self+neighbors, data = gerber, family = binomial)
summary(model)
pred = predict(model, type = "response")
table(gerber$voting,pred>.3)
(134513+51966)/(134513+51966+56730+100875)
table(gerber$voting,pred>.5)
235388/(235388+108696)
library(ROCR)
Rpred = prediction(pred,gerber$voting)
auc= as.numeric(performance(Rpred,"auc")@y.values)
auc
library(rpart)
library(rpart.plot)
CARTmodel = rpart(voting ~ civicduty + hawthorne + self + neighbors, data=gerber)
prp(CARTmodel)
CARTmodel2 = rpart(voting ~ civicduty + hawthorne + self + neighbors, data=gerber, cp=0.0)
prp(CARTmodel2)
CARTmodel3 = rpart(voting ~ civicduty + hawthorne + self + neighbors+ sex, data=gerber, cp=0.0)
prp(CARTmodel3)
model2= rpart(voting ~ control, data = gerber, cp=0.0)
model3= rpart(voting ~ control+sex, data = gerber,cp=0.0)
prp(model2, digits=6)
prp(model3, digits = 6)
.34-.296638
model4 = glm(voting~sex+control,data=gerber,family = binomial)
summary(model4)
CARTmodel4 = rpart(voting~sex+control,data=gerber)
possibility = data.frame(sex=c(0,0,1,1),control=c(1,0,1,0))
pred2 = predict(model4, newdata = possibility,type = "response")
pred3 = predict(CARTmodel4, newdata = possibility)
table(possibility,pred2)
pred2
pred3
0.3337375 -0.3158996
Model5 = glm(voting ~ sex + control + sex:control, data=gerber, family="binomial")
summary(Model5)
pred4=predict(Model5, newdata=possibility, type="response")
pred4
pred3
0.3341757-0.3158996
